package com.cskaoyan.mapper.yangtao;

import com.cskaoyan.domain.yangtao.Process;

import java.util.List;

public interface ProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 09 16:57:02 CST 2018
     */
    int deleteByPrimaryKey(String processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 09 16:57:02 CST 2018
     */
    int insert(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 09 16:57:02 CST 2018
     */
    int insertSelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 09 16:57:02 CST 2018
     */
    Process selectByPrimaryKey(String processId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 09 16:57:02 CST 2018
     */
    int updateByPrimaryKeySelective(Process record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table process
     *
     * @mbg.generated Sun Dec 09 16:57:02 CST 2018
     */
    int updateByPrimaryKey(Process record);

    List<Process> findAllProcessFromDB();
}