package com.cskaoyan.mapper.yangtao;

import com.cskaoyan.domain.yangtao.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    int deleteByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    Product selectByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    int updateByPrimaryKey(Product record);

    List<Product> findAllProductsFromDB();

    Product findProductByNameFromDB(@Param("searchValue") String searchValue);

    List<Product> findProductListByNameFromDB(@Param("searchValue") String searchValue);

    List<Product> findProductListByTypeFromDB(@Param("searchValue") String searchValue);
}