package com.cskaoyan.mapper.yangtao;

import com.cskaoyan.domain.yangtao.Task;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Dec 06 22:28:46 CST 2018
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Dec 06 22:28:46 CST 2018
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Dec 06 22:28:46 CST 2018
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Dec 06 22:28:46 CST 2018
     */
    Task selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Dec 06 22:28:46 CST 2018
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated Thu Dec 06 22:28:46 CST 2018
     */
    int updateByPrimaryKey(Task record);


    List<Task> findAllTasksFromDB();

    @Select("select count(*) from task")
    int findTasksCountFromDB();

    List<Task> findTaskByTaskWorkIdFromDB(@Param("searchValue") String searchValue);

    List<Task> findTaskBytaskManufactureSnFromDB(@Param("searchValue")String searchValue);
}