package com.cskaoyan.mapper.yangtao;

import com.cskaoyan.domain.yangtao.Work;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Sun Dec 09 16:54:23 CST 2018
     */
    int deleteByPrimaryKey(String workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Sun Dec 09 16:54:23 CST 2018
     */
    int insert(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Sun Dec 09 16:54:23 CST 2018
     */
    int insertSelective(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Sun Dec 09 16:54:23 CST 2018
     */
    Work selectByPrimaryKey(String workId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Sun Dec 09 16:54:23 CST 2018
     */
    int updateByPrimaryKeySelective(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbg.generated Sun Dec 09 16:54:23 CST 2018
     */
    int updateByPrimaryKey(Work record);

    List<Work> findAllWorksFromDB();

    List<Work> findWorklistByProductIdFromDB(@Param("theProductId") String theProductId);

    List<Work> findWorklistByDeviceIdFromDB(@Param("theDeviceId") String theDeviceId);

    List<Work> findWorkListByProcessIdFromDB(@Param("searchValue") String searchValue);
}