package com.cskaoyan.mapper.material;

import com.cskaoyan.domain.Material.M_Consume;
import com.cskaoyan.domain.Material.Vo.MaterialConsumeVO;

import java.util.List;

public interface M_ConsumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_consume
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int deleteByPrimaryKey(String consumeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_consume
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int insert(M_Consume record);
    //int insertMVo(MaterialConsumeVO materialConsumeVO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_consume
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int insertSelective(M_Consume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_consume
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    M_Consume selectByPrimaryKey(String consumeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_consume
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int updateByPrimaryKeySelective(M_Consume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_consume
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
     int updateByPrimaryKey(M_Consume record);
     List<MaterialConsumeVO> find( MaterialConsumeVO materialConsume);
     List<MaterialConsumeVO> searchMaterialConsumeByConsumeId(String consumeId);

     List<MaterialConsumeVO> searchMaterialConsumeByMaterialId(String materialId);

     List<MaterialConsumeVO> searchMaterialConsumeByWorkId(String workId);

}