package com.cskaoyan.mapper.material;

import com.cskaoyan.domain.Material.M_Receive;
import com.cskaoyan.domain.Material.Material;

import java.util.List;
import java.util.Map;


public interface M_ReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_receive
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int deleteByPrimaryKey(String receiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_receive
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int insert(M_Receive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_receive
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int insertSelective(M_Receive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_receive
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    M_Receive selectByPrimaryKey(String receiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_receive
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int updateByPrimaryKeySelective(M_Receive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table material_receive
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int updateByPrimaryKey(M_Receive record);

    List<M_Receive> selectAll();
     List<M_Receive> find();
    List SearchMaterialReceiveByMaterialId(String searchValue);
    List searchMaterialReceiveByReceiveId(String searchValue);
}

