package com.cskaoyan.mapper.material;

import com.cskaoyan.domain.Material.Material;

import java.util.List;
import java.util.Map;

public interface MaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int deleteByPrimaryKey(String materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int insertSelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    Material selectByPrimaryKey(String materialId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int updateByPrimaryKeySelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Material
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    int updateByPrimaryKey(Material record);
    //List<Material> getdata();
     List<Material> selectByPage();
     List<Material> selectMaterialByID(String searchValue);
     List<Material> SearchMaterialByMaterialType(String searchValue);
}