package com.cskaoyan.domain.yangtao;

public class Custom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_id
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private String customId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.custom_name
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private String customName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.full_name
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.address
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.fax
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.email
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.owner_name
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private String ownerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.owner_tel
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private String ownerTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.status
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.note
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_id
     *
     * @return the value of custom.custom_id
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public String getCustomId() {
        return customId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_id
     *
     * @param customId the value for custom.custom_id
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setCustomId(String customId) {
        this.customId = customId == null ? null : customId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.custom_name
     *
     * @return the value of custom.custom_name
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.custom_name
     *
     * @param customName the value for custom.custom_name
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.full_name
     *
     * @return the value of custom.full_name
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.full_name
     *
     * @param fullName the value for custom.full_name
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.address
     *
     * @return the value of custom.address
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.address
     *
     * @param address the value for custom.address
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.fax
     *
     * @return the value of custom.fax
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.fax
     *
     * @param fax the value for custom.fax
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.email
     *
     * @return the value of custom.email
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.email
     *
     * @param email the value for custom.email
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.owner_name
     *
     * @return the value of custom.owner_name
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.owner_name
     *
     * @param ownerName the value for custom.owner_name
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.owner_tel
     *
     * @return the value of custom.owner_tel
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public String getOwnerTel() {
        return ownerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.owner_tel
     *
     * @param ownerTel the value for custom.owner_tel
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setOwnerTel(String ownerTel) {
        this.ownerTel = ownerTel == null ? null : ownerTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.status
     *
     * @return the value of custom.status
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.status
     *
     * @param status the value for custom.status
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.note
     *
     * @return the value of custom.note
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.note
     *
     * @param note the value for custom.note
     *
     * @mbg.generated Sat Dec 08 11:03:32 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    @Override
    public String toString() {
        return "Custom{" +
                "customId='" + customId + '\'' +
                ", customName='" + customName + '\'' +
                ", fullName='" + fullName + '\'' +
                ", address='" + address + '\'' +
                ", fax='" + fax + '\'' +
                ", email='" + email + '\'' +
                ", ownerName='" + ownerName + '\'' +
                ", ownerTel='" + ownerTel + '\'' +
                ", status=" + status +
                ", note='" + note + '\'' +
                '}';
    }
}