package com.cskaoyan.domain.Material;



import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;

public class M_Receive {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_receive.receive_id
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private String receiveId;

    private Material material;

    public Material getMaterial() {
        return material;
    }

    public void setMaterial(Material material)
    {
        this.material = material;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_receive.material_id
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private String materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_receive.amount
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_receive.receive_date
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private Date  receiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_receive.sender
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_receive.receiver
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column material_receive.note
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_receive.receive_id
     *
     * @return the value of material_receive.receive_id
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public String getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_receive.receive_id
     *
     * @param receiveId the value for material_receive.receive_id
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setReceiveId(String receiveId) {
        this.receiveId = receiveId == null ? null : receiveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_receive.material_id
     *
     * @return the value of material_receive.material_id
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public String getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_receive.material_id
     *
     * @param materialId the value for material_receive.material_id
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setMaterialId(String materialId) {
        this.materialId = materialId == null ? null : materialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_receive.amount
     *
     * @return the value of material_receive.amount
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_receive.amount
     *
     * @param amount the value for material_receive.amount
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_receive.receive_date
     *
     * @return the value of material_receive.receive_date
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public Date getReceiveDate() {
        return receiveDate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_receive.receive_date
     *
     * @param receiveDate the value for material_receive.receive_date
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setReceiveDate(String receiveDate) throws ParseException {
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        this.receiveDate=sdf.parse(receiveDate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_receive.sender
     *
     * @return the value of material_receive.sender
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_receive.sender
     *
     * @param sender the value for material_receive.sender
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_receive.receiver
     *
     * @return the value of material_receive.receiver
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_receive.receiver
     *
     * @param receiver the value for material_receive.receiver
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column material_receive.note
     *
     * @return the value of material_receive.note
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column material_receive.note
     *
     * @param note the value for material_receive.note
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}