package com.cskaoyan.domain.Material;

public class Material {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.material_id
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private String materialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.material_type
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private String materialType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.status
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.remaining
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private Integer remaining;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Material.note
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.material_id
     *
     * @return the value of Material.material_id
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public String getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.material_id
     *
     * @param materialId the value for Material.material_id
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setMaterialId(String materialId) {
        this.materialId = materialId == null ? null : materialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.material_type
     *
     * @return the value of Material.material_type
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public String getMaterialType() {
        return materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.material_type
     *
     * @param materialType the value for Material.material_type
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setMaterialType(String materialType) {
        this.materialType = materialType == null ? null : materialType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.status
     *
     * @return the value of Material.status
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.status
     *
     * @param status the value for Material.status
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.remaining
     *
     * @return the value of Material.remaining
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public Integer getRemaining() {
        return remaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.remaining
     *
     * @param remaining the value for Material.remaining
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setRemaining(Integer remaining) {
        this.remaining = remaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Material.note
     *
     * @return the value of Material.note
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Material.note
     *
     * @param note the value for Material.note
     *
     * @mbg.generated Fri Dec 07 21:26:47 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}