package com.cskaoyan.mapper;

import com.cskaoyan.domain.Corder;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Dec 07 22:28:08 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Dec 07 22:28:08 CST 2018
     */
    int insert(Corder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Dec 07 22:28:08 CST 2018
     */
    int insertSelective(Corder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Dec 07 22:28:08 CST 2018
     */
    Corder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Dec 07 22:28:08 CST 2018
     */
    int updateByPrimaryKeySelective(Corder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_order
     *
     * @mbg.generated Fri Dec 07 22:28:08 CST 2018
     */
    int updateByPrimaryKey(Corder record);

    List<Corder> findAllOrderFromDB();

    List<Corder> findOrdersByCustomIdFromDB(@Param("theCustomID") String theCustomID);

    List<Corder> findOrderByProductIdFromDB(@Param("theProductId") String theProductId);
}