package com.cskaoyan.mapper;

import com.cskaoyan.domain.Device;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun Dec 09 17:00:12 CST 2018
     */
    int deleteByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun Dec 09 17:00:12 CST 2018
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun Dec 09 17:00:12 CST 2018
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun Dec 09 17:00:12 CST 2018
     */
    Device selectByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun Dec 09 17:00:12 CST 2018
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun Dec 09 17:00:12 CST 2018
     */
    int updateByPrimaryKey(Device record);

    List<Device> findAllDevicesFromDB();

    Device findDeviceByNameFromDB(@Param("searchValue") String searchValue);
}